/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0xC40000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x0EU /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_EMC_08 (coord H3), motorXa */
/* Routed pin properties */
#define BOARD_INITPINS_motorXa_PERIPHERAL                                   PWM2   /*!< Peripheral name */
#define BOARD_INITPINS_motorXa_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITPINS_motorXa_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_EMC_06 (coord H5), motorXb */
/* Routed pin properties */
#define BOARD_INITPINS_motorXb_PERIPHERAL                                   PWM2   /*!< Peripheral name */
#define BOARD_INITPINS_motorXb_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITPINS_motorXb_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_AD_B1_09 (coord M13), motorYa */
/* Routed pin properties */
#define BOARD_INITPINS_motorYa_PERIPHERAL                                   PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_motorYa_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITPINS_motorYa_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_AD_B1_08 (coord H13), motorYb */
/* Routed pin properties */
#define BOARD_INITPINS_motorYb_PERIPHERAL                                   PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_motorYb_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITPINS_motorYb_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_B0_02 (coord E8), encoderXa */
/* Routed pin properties */
#define BOARD_INITPINS_encoderXa_PERIPHERAL                                GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_encoderXa_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_encoderXa_CHANNEL                                      2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_encoderXa_GPIO                                      GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_encoderXa_GPIO_PIN                                     2U   /*!< GPIO pin number */
#define BOARD_INITPINS_encoderXa_GPIO_PIN_MASK                        (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_encoderXa_PORT                                      GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_encoderXa_PIN                                          2U   /*!< PORT pin number */
#define BOARD_INITPINS_encoderXa_PIN_MASK                             (1U << 2U)   /*!< PORT pin mask */

/* GPIO_B0_01 (coord E7), encoderXb */
/* Routed pin properties */
#define BOARD_INITPINS_encoderXb_PERIPHERAL                                GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_encoderXb_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_encoderXb_CHANNEL                                      1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_encoderXb_GPIO                                      GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_encoderXb_GPIO_PIN                                     1U   /*!< GPIO pin number */
#define BOARD_INITPINS_encoderXb_GPIO_PIN_MASK                        (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_encoderXb_PORT                                      GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_encoderXb_PIN                                          1U   /*!< PORT pin number */
#define BOARD_INITPINS_encoderXb_PIN_MASK                             (1U << 1U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (coord J12), encoderYa */
/* Routed pin properties */
#define BOARD_INITPINS_encoderYa_PERIPHERAL                                GPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_encoderYa_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_encoderYa_CHANNEL                                     22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_encoderYa_GPIO                                      GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_encoderYa_GPIO_PIN                                    22U   /*!< GPIO pin number */
#define BOARD_INITPINS_encoderYa_GPIO_PIN_MASK                       (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_encoderYa_PORT                                      GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_encoderYa_PIN                                         22U   /*!< PORT pin number */
#define BOARD_INITPINS_encoderYa_PIN_MASK                            (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (coord K10), encoderYb */
/* Routed pin properties */
#define BOARD_INITPINS_encoderYb_PERIPHERAL                                GPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_encoderYb_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_encoderYb_CHANNEL                                     23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_encoderYb_GPIO                                      GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_encoderYb_GPIO_PIN                                    23U   /*!< GPIO pin number */
#define BOARD_INITPINS_encoderYb_GPIO_PIN_MASK                       (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_encoderYb_PORT                                      GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_encoderYb_PIN                                         23U   /*!< PORT pin number */
#define BOARD_INITPINS_encoderYb_PIN_MASK                            (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B1_02 (coord L11), loadButton */
/* Routed pin properties */
#define BOARD_INITPINS_loadButton_PERIPHERAL                               GPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_loadButton_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_loadButton_CHANNEL                                    18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_loadButton_GPIO                                     GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_loadButton_GPIO_PIN                                   18U   /*!< GPIO pin number */
#define BOARD_INITPINS_loadButton_GPIO_PIN_MASK                      (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_loadButton_PORT                                     GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_loadButton_PIN                                        18U   /*!< PORT pin number */
#define BOARD_INITPINS_loadButton_PIN_MASK                           (1U << 18U)   /*!< PORT pin mask */

/* GPIO_B0_03 (coord D8), headSolenoid */
/* Routed pin properties */
#define BOARD_INITPINS_headSolenoid_PERIPHERAL                             GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_headSolenoid_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_headSolenoid_CHANNEL                                   3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_headSolenoid_GPIO                                   GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_headSolenoid_GPIO_PIN                                  3U   /*!< GPIO pin number */
#define BOARD_INITPINS_headSolenoid_GPIO_PIN_MASK                     (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_headSolenoid_PORT                                   GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_headSolenoid_PIN                                       3U   /*!< PORT pin number */
#define BOARD_INITPINS_headSolenoid_PIN_MASK                          (1U << 3U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
